### ISSUE TITLE
Mysqld module errors

### ISSUE THREAD

**Issue by cyberflow** [ganglia/gmond_python_modules#163]
If i try add module to ganglia i get error in logs:

```
/usr/sbin/gmond[3861]: [PYTHON] Can't call the metric_init function in the python module [mysql].#012
```

if i try run module form console:

```
# python /usr/lib/ganglia/python_modules/mysql.py -u root -p password --no-master --no-slave
Traceback (most recent call last):
  File "/usr/lib/ganglia/python_modules/mysql.py", line 1160, in <module>
    'unix_socket': options.unix_socket,
  File "/usr/lib/ganglia/python_modules/mysql.py", line 1095, in metric_init
    update_stats(REPORT_INNODB, REPORT_MASTER, REPORT_SLAVE)
  File "/usr/lib/ganglia/python_modules/mysql.py", line 266, in update_stats
    mysql_stats[key] = int(global_status[key]) - int(mysql_stats_last[key])
ValueError: invalid literal for int() with base 10: ''
```

**Comment by vvuksan** [comment]
@chuckpu can you submit a pull request ?

Thanks
